swagger: "2.0"
info:
  description: Swagger doc for /api/sys/firmware_info_pim
  title: Swagger doc for /api/sys/firmware_info_pim
  version: 1.0.0
paths:
  /api/sys/firmware_info_pim:
    get:
      produces: [application/json]
      responses:
        200:
          description: ok
          schema:
            type: object
            additionalProperties: false
            properties:
              Resources:
                type: array
                items:
                  type: string
              Actions:
                type: array
                items:
                  type: string
              Information:
                type: object
                additionalProperties: false
                properties:
                  1:
                    type: object
                    properties:
                      type:
                        type: string
                      version:
                        type: string
                      status:
                        type: string
                    required:
                      - status
                  2:
                    type: object
                    properties:
                      type:
                        type: string
                      version:
                        type: string
                      status:
                        type: string
                    required:
                      - status
                  3:
                    type: object
                    properties:
                      type:
                        type: string
                      version:
                        type: string
                      status:
                        type: string
                    required:
                      - status
                  4:
                    type: object
                    properties:
                      type:
                        type: string
                      version:
                        type: string
                      status:
                        type: string
                    required:
                      - status
                  5:
                    type: object
                    properties:
                      type:
                        type: string
                      version:
                        type: string
                      status:
                        type: string
                    required:
                      - status
                  6:
                    type: object
                    properties:
                      type:
                        type: string
                      version:
                        type: string
                      status:
                        type: string
                    required:
                      - status
                  7:
                    type: object
                    properties:
                      type:
                        type: string
                      version:
                        type: string
                      status:
                        type: string
                    required:
                      - status
                  8:
                    type: object
                    properties:
                      type:
                        type: string
                      version:
                        type: string
                      status:
                        type: string
                    required:
                      - status
