swagger: "2.0"
info:
  description: Swagger doc for /api/sys/pimdetails
  title: Swagger doc for /api/sys/pimdetails
  version: 1.0.0
paths:
  /api/sys/pimdetails:
    get:
      produces: [application/json]
      responses:
        200:
          description: ok
          schema:
            type: object
            additionalProperties: false
            properties:
              1:
                type: object
                additionalProperties: false
                properties:
                  status:
                    type: string
                  reason:
                    type: string
                  version:
                    type: string
                  product_name:
                    type: string
                  product_part_number:
                    type: string
                  system_assembly_part_number:
                    type: string
                  facebook_pcba_part_number:
                    type: string
                  facebook_pcb_part_number:
                    type: string
                  odm_pcba_part_number:
                    type: string
                  odm_pcba_serial_number:
                    type: string
                  product_production_state:
                    type: string
                  product_version:
                    type: string
                  product_sub_version:
                    type: string
                  product_serial_number:
                    type: string
                  product_asset_tag:
                    type: string
                  system_manufacturer:
                    type: string
                  system_manufacturing_date:
                    type: string
                  pcb_manufacturer:
                    type: string
                  assembled_at:
                    type: string
                  local_mac:
                    type: string
                  extended_mac_base:
                    type: string
                  extended_mac_address_size:
                    type: string
                  location_on_fabric:
                    type: string
                  crc8:
                    type: string
                required:
                  - status
              2:
                type: object
                additionalProperties: false
                properties:
                  status:
                    type: string
                  reason:
                    type: string
                  version:
                    type: string
                  product_name:
                    type: string
                  product_part_number:
                    type: string
                  system_assembly_part_number:
                    type: string
                  facebook_pcba_part_number:
                    type: string
                  facebook_pcb_part_number:
                    type: string
                  odm_pcba_part_number:
                    type: string
                  odm_pcba_serial_number:
                    type: string
                  product_production_state:
                    type: string
                  product_version:
                    type: string
                  product_sub_version:
                    type: string
                  product_serial_number:
                    type: string
                  product_asset_tag:
                    type: string
                  system_manufacturer:
                    type: string
                  system_manufacturing_date:
                    type: string
                  pcb_manufacturer:
                    type: string
                  assembled_at:
                    type: string
                  local_mac:
                    type: string
                  extended_mac_base:
                    type: string
                  extended_mac_address_size:
                    type: string
                  location_on_fabric:
                    type: string
                  crc8:
                    type: string
                required:
                  - status
              3:
                type: object
                additionalProperties: false
                properties:
                  state:
                    type: string
                  reason:
                    type: string
                  version:
                    type: string
                  product_name:
                    type: string
                  product_part_number:
                    type: string
                  system_assembly_part_number:
                    type: string
                  facebook_pcba_part_number:
                    type: string
                  facebook_pcb_part_number:
                    type: string
                  odm_pcba_part_number:
                    type: string
                  odm_pcba_serial_number:
                    type: string
                  product_production_state:
                    type: string
                  product_version:
                    type: string
                  product_sub_version:
                    type: string
                  product_serial_number:
                    type: string
                  product_asset_tag:
                    type: string
                  system_manufacturer:
                    type: string
                  system_manufacturing_date:
                    type: string
                  pcb_manufacturer:
                    type: string
                  assembled_at:
                    type: string
                  local_mac:
                    type: string
                  extended_mac_base:
                    type: string
                  extended_mac_address_size:
                    type: string
                  location_on_fabric:
                    type: string
                  crc8:
                    type: string
                required:
                  - status
              4:
                type: object
                additionalProperties: false
                properties:
                  state:
                    type: string
                  reason:
                    type: string
                  version:
                    type: string
                  product_name:
                    type: string
                  product_part_number:
                    type: string
                  system_assembly_part_number:
                    type: string
                  facebook_pcba_part_number:
                    type: string
                  facebook_pcb_part_number:
                    type: string
                  odm_pcba_part_number:
                    type: string
                  odm_pcba_serial_number:
                    type: string
                  product_production_state:
                    type: string
                  product_version:
                    type: string
                  product_sub_version:
                    type: string
                  product_serial_number:
                    type: string
                  product_asset_tag:
                    type: string
                  system_manufacturer:
                    type: string
                  system_manufacturing_date:
                    type: string
                  pcb_manufacturer:
                    type: string
                  assembled_at:
                    type: string
                  local_mac:
                    type: string
                  extended_mac_base:
                    type: string
                  extended_mac_address_size:
                    type: string
                  location_on_fabric:
                    type: string
                  crc8:
                    type: string
                required:
                  - status
              5:
                type: object
                additionalProperties: false
                properties:
                  status:
                    type: string
                  reason:
                    type: string
                  version:
                    type: string
                  product_name:
                    type: string
                  product_part_number:
                    type: string
                  system_assembly_part_number:
                    type: string
                  facebook_pcba_part_number:
                    type: string
                  facebook_pcb_part_number:
                    type: string
                  odm_pcba_part_number:
                    type: string
                  odm_pcba_serial_number:
                    type: string
                  product_production_state:
                    type: string
                  product_version:
                    type: string
                  product_sub_version:
                    type: string
                  product_serial_number:
                    type: string
                  product_asset_tag:
                    type: string
                  system_manufacturer:
                    type: string
                  system_manufacturing_date:
                    type: string
                  pcb_manufacturer:
                    type: string
                  assembled_at:
                    type: string
                  local_mac:
                    type: string
                  extended_mac_base:
                    type: string
                  extended_mac_address_size:
                    type: string
                  location_on_fabric:
                    type: string
                  crc8:
                    type: string
                required:
                  - status

              6:
                type: object
                additionalProperties: false
                properties:
                  status:
                    type: string
                  reason:
                    type: string
                  version:
                    type: string
                  product_name:
                    type: string
                  product_part_number:
                    type: string
                  system_assembly_part_number:
                    type: string
                  facebook_pcba_part_number:
                    type: string
                  facebook_pcb_part_number:
                    type: string
                  odm_pcba_part_number:
                    type: string
                  odm_pcba_serial_number:
                    type: string
                  product_production_state:
                    type: string
                  product_version:
                    type: string
                  product_sub_version:
                    type: string
                  product_serial_number:
                    type: string
                  product_asset_tag:
                    type: string
                  system_manufacturer:
                    type: string
                  system_manufacturing_date:
                    type: string
                  pcb_manufacturer:
                    type: string
                  assembled_at:
                    type: string
                  local_mac:
                    type: string
                  extended_mac_base:
                    type: string
                  extended_mac_address_size:
                    type: string
                  location_on_fabric:
                    type: string
                  crc8:
                    type: string
                required:
                  - status

              7:
                type: object
                additionalProperties: false
                properties:
                  status:
                    type: string
                  reason:
                    type: string
                  version:
                    type: string
                  product_name:
                    type: string
                  product_part_number:
                    type: string
                  system_assembly_part_number:
                    type: string
                  facebook_pcba_part_number:
                    type: string
                  facebook_pcb_part_number:
                    type: string
                  odm_pcba_part_number:
                    type: string
                  odm_pcba_serial_number:
                    type: string
                  product_production_state:
                    type: string
                  product_version:
                    type: string
                  product_sub_version:
                    type: string
                  product_serial_number:
                    type: string
                  product_asset_tag:
                    type: string
                  system_manufacturer:
                    type: string
                  system_manufacturing_date:
                    type: string
                  pcb_manufacturer:
                    type: string
                  assembled_at:
                    type: string
                  local_mac:
                    type: string
                  extended_mac_base:
                    type: string
                  extended_mac_address_size:
                    type: string
                  location_on_fabric:
                    type: string
                  crc8:
                    type: string
                required:
                  - status

              8:
                type: object
                additionalProperties: false
                properties:
                  status:
                    type: string
                  reason:
                    type: string
                  version:
                    type: string
                  product_name:
                    type: string
                  product_part_number:
                    type: string
                  system_assembly_part_number:
                    type: string
                  facebook_pcba_part_number:
                    type: string
                  facebook_pcb_part_number:
                    type: string
                  odm_pcba_part_number:
                    type: string
                  odm_pcba_serial_number:
                    type: string
                  product_production_state:
                    type: string
                  product_version:
                    type: string
                  product_sub_version:
                    type: string
                  product_serial_number:
                    type: string
                  product_asset_tag:
                    type: string
                  system_manufacturer:
                    type: string
                  system_manufacturing_date:
                    type: string
                  pcb_manufacturer:
                    type: string
                  assembled_at:
                    type: string
                  local_mac:
                    type: string
                  extended_mac_base:
                    type: string
                  extended_mac_address_size:
                    type: string
                  location_on_fabric:
                    type: string
                  crc8:
                    type: string
                required:
                  - status
