swagger: "2.0"
info: 
  description: Swagger doc for /api/sys/firmware_info/internal_switch_config  
  title: Swagger doc for /api/sys/firmware_info/internal_switch_config  
  version: 1.0.0
paths: 
  /api/sys/firmware_info/internal_switch_config: 
    get: 
      produces: [application/json]
      responses: 
        200: 
          description: ok
          schema: 
            type: object
            additionalProperties: false
            properties: 
              INTERNAL_SWITCH_CONFIG: 
                type: string
