swagger: "2.0"
info:
  description: Swagger doc for /api/sys/firmware_info/sys
  title: Swagger doc for /api/sys/firmware_info/sys
  version: 1.0.0
paths:
  /api/sys/firmware_info/sys:
    get:
      produces: [application/json]
      responses:
        200:
          description: ok
          schema:
            type: object
            additionalProperties: false
            properties:
              SYS_CPLD:
                type: string
